spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/order_book?createDatabaseIfNotExist=true
    username: terareum
    password: Terareum@2023
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update

server:
  port: 8002

